# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: hello                              # 网站的标题，可能用在各种布局的页面中
subtitle:                                 # 网站子标题
description:                              # 网站的描述性
keywords:                                 # 网站的关键字
author: lessthan4408@163.com              # 网站的作者
language: zh-CN                           # 网站采用语言，要跟/theme/***/languages/**.yml下的文件名对应。
timezone: Asia/Shanghai                   # 网站的时区

# URL
url: https://s1xpences.github.io/         # 网站的url，如果不在域名根目录，应包含子目录，且root要设置为`/子目录/`
root: /                                   # 网站的根目录
permalink: :year/:month/:day/:title/      #文章永久链接的形成模版。每一篇文章都有唯一的url。
permalink_defaults:                       #文章永久链接中，各部分的默认值。
pretty_urls:                              #改写 permalink 的值来美化 URL
  trailing_index: true                    #是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_html: true                     #是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)

# Directory
source_dir: source                        #资源文件夹，这个文件夹用来存放内容。
public_dir: public                        #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags                             #标签文件夹
archive_dir: archives                     #归档文件夹
category_dir: categories                  #分类文件夹
code_dir: downloads/code                  #Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang                           #国际化（i18n）文件夹
skip_render:                              #跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。

# Writing
new_post_name: :title.md                  #新文章的文件名称
default_layout: post                      #预设布局
titlecase: false                          #把标题转换为 title case
external_link:                            #在新标签中打开链接
  enable: true                            #在新标签中打开链接
  field: site                             #对整个网站（site）生效或仅对文章（post）生效
  exclude: ''                             #需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0                          #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false                      #显示草稿
post_asset_folder: false                  #启动 Asset 文件夹
relative_link: false                      #把链接改为与根目录的相对位址
future: true                              #显示未来的文章
highlight:                                #代码块的设置, see Highlight.js section for usage guide
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:                                  #代码块的设置, see PrismJS section for usage guide
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:                                        
  path: ''                               # path: Root path for your blogs index page. (default = '')
  per_page: 10                           # per_page: Posts displayed per page. (0 = disable pagination)
  order_by: -date                        # order_by: Posts order. (Order by date descending by default)

# Category & Tag
default_category: uncategorized          #默认分类
category_map:                            #分类别名
tag_map:                                 #标签别名

# Metadata elements
meta_generator: true                     # Meta generator 标签。 值为 false 时 Hexo 不会在头部插入该标签

# Date / Time format
date_format: YYYY-MM-DD                  # http://momentjs.com/docs/#/displaying/format/
time_format: HH:mm:ss
updated_option: 'mtime'                  # updated_option supports 'mtime', 'date', 'empty'

# Pagination
per_page: 10                             #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page                     #分页目录

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: next                               #当前主题名称。值为false时禁用主题

# Deployment
deploy:                                   #部署部分的设置
  type: 'git'
  repo: https://github.com/s1xpences/s1xpences.github.io.git
  branch: 'server'
